---
title: "Clustering"
author: "Will Townes"
date: "4/30/2018"
output: html_document
---

PCA embeddings

```{r}
library(ggplot2)
library(dplyr)
ari<-mclust::adjustedRandIndex
fp<-file.path
```

First get the data from the ipython colab. Download the embeddings of cells for each hyperparam setting to embeddings/cortex.

```{r}
clust2ari<-function(X_enc,labels){
  #X_enc has samples in rows and features in cols
  #runs hierarchical clustering and returns adjusted rand score compared to labels
  stopifnot(nrow(X_enc)==length(labels))
  cl<-NbClust::NbClust(d, method="ward.D2", index="ch", min.nc=nlevels(labels), max.nc=nlevels(labels))$Best.partition
  ari(labels,cl)
}

dt<-"cortex"
labels<-read.csv("data/cortex/cell_info.csv")$level1class

dpth<-fp("data",dt,paste0(dt,"_expression.txt"))
Y<-t(as.matrix(read.table(dpth))) #ncells x ngenes
Yl2<-log2(1+Y/rowSums(Y)*1e6)
pca<-prcomp(Yl2,center=TRUE,scale=TRUE)$x
```

```{r}
pth<-fp("embeddings",dt)
opth<-fp("results",dt)

model<-c("bernoulli","gaussian","poisson","negative_binomial","pca")
nbshapes<-data.frame(a=c(.1,1,10),astr=c("01","1","10"))
hnodes<-c("200","500")
latent_dims<-c("2","10","50")

#nonlinear except neg binom
res1<-expand.grid(model=model[1:3], latent_dimension=latent_dims, hidden_width=hnodes, nbshape=NA, adj_rand_index=NA)
#nonlinear neg binom
res2<-expand.grid(model="negative_binomial", latent_dimension=latent_dims, hidden_width=hnodes, nbshape=nbshapes$astr, adj_rand_index=NA)
#pca
res3<-expand.grid(model="pca", latent_dimension=latent_dims, hidden_width=NA,nbshape=NA,adj_rand_index=NA)
res<-rbind(res1,res2,res3)
for(i in seq.int(nrow(res))){
  l<-res[i,"model"]; d<-res[i,"latent_dimension"]; h<-res[i,"hidden_width"]
  if(l=="negative_binomial"){
    a<-res[i,"nbshape"]
    fname<-paste0(l,a,"_d",d,"_h",h)
  } else if(l!="pca"){
    fname<-paste0(l,"_d",d,"_h",h)
  }
  if(l!="pca"){
    d<-read.table(fp(pth,paste0(fname,".txt")))
  } else {
    d<-pca[,seq.int(as.integer(d))]
  }
  res[i,"adj_rand_index"]<-clust2ari(d,labels)
}
res$nbshape[res$nbshape=="01"]<-"0.1"
res$dataset<-dt
dir.create(opth,recursive=TRUE)
write.csv(res,fp(opth,"ari.csv"))
```

```{r}
pth<-"results/plots"
dir.create(pth,recursive=TRUE)
res<-read.csv("results/cortex/ari.csv")
res$latent_dims<-factor(res$latent_dimension,levels=c("2","10","50"))
res$hidden_width<-factor(res$hidden_width)
res$nbshape<-factor(res$nbshape)
res$model_type<-"vae"
res$model_type[res$model=="pca"]<-"pca"

#best loss func
res$model<-reorder(res$model,res$adj_rand_index)
ggplot(res,aes(x=model,y=adj_rand_index,fill=latent_dims))+geom_boxplot()+theme_bw()
ggsave(fp(pth,"cortex_ari_vs_loss.png"),width=6,height=4)

#res2<-subset(res,model!="negative_binomial")
#res2nb<-subset(res,model=="negative_binomial") %>% group_by(hidden_width,latent_dims) %>% summarise(adj_rand_index

#best hyperparameters
ggplot(subset(res,latent_dims %in% c("10","50")),aes(x=model,y=adj_rand_index,fill=hidden_width))+geom_boxplot()+theme_bw()
ggsave(fp(pth,"cortex_ari_vs_hidden_width.png"),width=6,height=3)

#best nbshape
ggplot(subset(res,model=="negative_binomial"),aes(x=latent_dims,y=adj_rand_index,colour=nbshape,group=nbshape))+geom_line(size=1.5)+facet_wrap(~hidden_width)+theme_bw()
ggsave(fp(pth,"cortex_ari_vs_nbshape.png"),width=6,height=3)
```
visualize embeddings
```{r}
losses<-c("bernoulli","gaussian","negative_binomial1","poisson")
f<-function(l){
  fname<-paste0(l,"_d2_h500.txt")
  d<-read.table(fp("embeddings/cortex",fname))
  colnames(d)<-paste0("dim",c(1,2))
  d$model<-l
  d$cell_types<-labels
  d
}
d<-lapply(losses,f)
names(d)<-losses
d$pca<-data.frame(pca[,1:2],model="pca",cell_types=labels)
colnames(d$pca)[1:2]<-c("dim1","dim2")
pd<-do.call("rbind",d)
ggplot(pd,aes(x=dim1,y=dim2,colour=cell_types))+geom_point(size=.1)+facet_wrap(~model,scales="free")+theme_bw()+theme(legend.position = "none")
ggsave("results/plots/cortex_2dvis_nolegend.png",width=6,height=3)
ggplot(pd,aes(x=dim1,y=dim2,colour=cell_types))+geom_point(size=2)+facet_wrap(~model,scales="free")+theme_bw()
ggsave("results/plots/cortex_2dvis_biglegend.png",width=6,height=3)
```
